const options = () => [
  { value: 'Comedy', label: 'Comedy' },
  { value: 'Romance', label: 'Romance' },
  { value: 'Romantic Comedy', label: 'Romantic Comedy' },
  { value: 'Action', label: 'Action' },
  { value: 'Adventure', label: 'Adventure' },
  { value: 'Fiction', label: 'Fiction' },
  { value: 'Science Fiction', label: 'Science Fiction' },
  { value: 'Dystopian Fiction', label: 'Dystopian Fiction' },
  { value: 'Fantasy', label: 'Fantasy' },
  { value: 'Superhero', label: 'Superhero' },
  { value: 'Drama', label: 'Drama' },
  { value: 'Horror', label: 'Horror' },
  { value: 'Thriller', label: 'Thriller' },
  { value: 'Thriller', label: 'Mystery' },
  { value: 'Musical', label: 'Musical' },
  { value: 'War', label: 'War' },
  { value: 'Crime', label: 'Crime' },
  { value: 'Western', label: 'Western' },
  { value: 'Disaster', label: 'Disaster' },
  { value: 'Animation', label: 'Animation' },
  { value: 'Historical', label: 'Historical' },
  { value: 'Biographical', label: 'Biographical' },
  { value: 'Sports', label: 'Sports' },
  { value: 'Spy', label: 'Spy' },
  { value: 'Martial Arts', label: 'Martial Arts' },
];

export default options;
